version: "3"
volumes:
  logs.app:
  cache.app:
services:
  nginx:
    container_name: nginx.frame
    build:
      context: ./
      dockerfile: Dockerfile_NGINX
    ports:
      - "8000:80"
    links:
      - php
    volumes:
      - ./:/frame
      - logs.app:/app/var/logs
      - cache.app:/app/var/cache
      - ./host.conf:/etc/nginx/conf.d/default.conf
  php:
    container_name: php.frame
    build:
      context: ./
      dockerfile: Dockerfile_PHP
    links:
      - db
    volumes:
      - ./:/frame
      - logs.app:/app/var/logs
      - cache.app:/app/var/cache
  db:
    container_name: postgres.frame
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "123"

       # Default user: postgres
  adminer:
    container_name: adminer.frame
    image: adminer
    ports:
      - "8080:8080"
    links:
      - db
    environment:
      ADMINER_PLUGINS: "tables-filter tinymce"
